skips:
- B101  # assert_used, needed for mypy
- B320  # xml_bad_etree
- B321  # ftplib, https://github.com/scrapy/scrapy/issues/4180
- B324  # hashlib "Use of weak SHA1 hash for security"
- B402  # import_ftplib, https://github.com/scrapy/scrapy/issues/4180
- B410  # import_lxml
- B411  # import_xmlrpclib, https://github.com/PyCQA/bandit/issues/1082
- B503  # ssl_with_bad_defaults
exclude_dirs: ['tests']
